apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  namespace: unix-socket
  name: recording-server
spec:
  kind: SelinuxProfile
  recorder: logs
  podSelector:
    matchLabels:
      name: server
